name: chat_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  outline_gradient_button: ^2.0.1+1
  gap: ^2.0.1
  grouped_list: ^5.1.2
  intl: ^0.18.0
  http: ^1.1.2
  file_picker: ^6.1.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  socket_io_client: ^2.0.3+1
  emoji_picker_flutter: ^1.6.3
  flutter_contacts: ^1.1.7+1
  web_socket_channel: ^2.4.0
  redis: ^4.0.0
  io: ^1.0.4
  chat_bubbles: ^1.5.0
  flutter_chat_bubble: ^2.0.2
  image_picker: ^1.0.7
  at_invitation_flutter: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Copse
      fonts: 
        - asset: assets/fonts/Copse.ttf
          weight: 400
    - family: Cormorant Upright
      fonts: 
        - asset: assets/fonts/CormorantUprightRegular.ttf
          weight: 400
        - asset: assets/fonts/CormorantUprightBold.ttf
          weight: 700
    - family: Chivo
      fonts: 
        - asset: assets/fonts/ChivoLight.ttf
          weight: 400
        - asset: assets/fonts/ChivoRegular.ttf
          weight: 400
        - asset: assets/fonts/ChivoBold.ttf
          weight: 400
        - asset: assets/fonts/ChivoBlack.ttf
          weight: 900
        - asset: assets/fonts/ChivoItalic.ttf
          weight: 400
    - family: Croissant One
      fonts: 
        - asset: assets/fonts/CroissantOneRegular.ttf
          weight: 400
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/MulishRomanExtraBlack.ttf
          weight: 900
    - family: Comfortaa
      fonts: 
        - asset: assets/fonts/ComfortaaRegular.ttf
          weight: 400
    - family: Adamina
      fonts: 
        - asset: assets/fonts/AdaminaRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
